# unless otherwise specified, hooks run on push only
default_stages: [push]
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        stages: [commit]
        entry: pipenv run black
        language: system
        types: [python]
        require_serial: true
